---
title: Service Design Library
author: Andy Williams-Jones
email: hello@awj.digital
description: A curated collection of techniques, tools and services for people in
  service design.
baseurl: "/ubuild-jekyll"
url: https://servicedesignlibrary.com
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
